load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

# Target to generate compile_commands.json for clangd / IDE navigation
refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = {
        "//...": "",
    },
)

alias(
    name = "safetensor_dmp",
    actual = "//lessons/lesson01:safetensor_dmp",
)

alias(
    name = "safetensors_dmp",
    actual = "//lessons/lesson01:safetensor_dmp",
)

alias(
    name = "safetensor_loader",
    actual = "//lessons/lesson01:safetensor_loader",
)
